[2025-05-24T12:19:06.579+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_data_pipeline.validate_contacts manual__2025-05-24T12:18:08.583052+00:00 [queued]>
[2025-05-24T12:19:07.222+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_data_pipeline.validate_contacts manual__2025-05-24T12:18:08.583052+00:00 [queued]>
[2025-05-24T12:19:07.358+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-24T12:19:07.512+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_contacts> on 2025-05-24 12:18:08.583052+00:00
[2025-05-24T12:19:07.560+0000] {standard_task_runner.py:60} INFO - Started process 420 to run task
[2025-05-24T12:19:07.624+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marketing_data_pipeline', 'validate_contacts', 'manual__2025-05-24T12:18:08.583052+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmpvc3uei_z']
[2025-05-24T12:19:07.651+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask validate_contacts
[2025-05-24T12:19:09.161+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_data_pipeline.validate_contacts manual__2025-05-24T12:18:08.583052+00:00 [running]> on host 00e321f10423
[2025-05-24T12:19:10.268+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='validate_contacts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-24T12:18:08.583052+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-24T12:18:08.583052+00:00'
[2025-05-24T12:19:10.318+0000] {main_pipeline_dag.py:25} INFO - ▶️ Starting task: Validate Contacts
[2025-05-24T12:19:10.557+0000] {data_validation.py:177} INFO - ⏩ Already validated: contacts_2025-05-24.csv
[2025-05-24T12:19:10.630+0000] {utils.py:52} INFO - task_metrics
[2025-05-24T12:19:10.758+0000] {main_pipeline_dag.py:27} INFO - ✅ Completed task: Validate Contacts
[2025-05-24T12:19:10.857+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-24T12:19:10.998+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=marketing_data_pipeline, task_id=validate_contacts, execution_date=20250524T121808, start_date=20250524T121907, end_date=20250524T121910
[2025-05-24T12:19:11.342+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-24T12:19:17.573+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
