[2025-05-24T18:37:53.420+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_data_pipeline.validate_contacts manual__2025-05-24T18:36:40.098209+00:00 [queued]>
[2025-05-24T18:37:53.486+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_data_pipeline.validate_contacts manual__2025-05-24T18:36:40.098209+00:00 [queued]>
[2025-05-24T18:37:53.488+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-24T18:37:53.589+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_contacts> on 2025-05-24 18:36:40.098209+00:00
[2025-05-24T18:37:53.632+0000] {standard_task_runner.py:60} INFO - Started process 287 to run task
[2025-05-24T18:37:53.650+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marketing_data_pipeline', 'validate_contacts', 'manual__2025-05-24T18:36:40.098209+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmputpvvjdy']
[2025-05-24T18:37:53.667+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask validate_contacts
[2025-05-24T18:37:53.992+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_data_pipeline.validate_contacts manual__2025-05-24T18:36:40.098209+00:00 [running]> on host 87457b4103d8
[2025-05-24T18:37:54.359+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='validate_contacts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-24T18:36:40.098209+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-24T18:36:40.098209+00:00'
[2025-05-24T18:37:54.366+0000] {main_pipeline_dag.py:25} INFO - ‚ñ∂Ô∏è Starting task: Validate Contacts
[2025-05-24T18:37:55.176+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-24.csv | schema_format = PASS
[2025-05-24T18:37:55.943+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-24.csv | freshness = PASS
[2025-05-24T18:37:56.707+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-24.csv | row_count = PASS
[2025-05-24T18:37:57.177+0000] {data_validation.py:139} INFO - Removed /opt/***/data/raw_data/contacts_2025-05-24.csv from raw_data folder
[2025-05-24T18:38:01.394+0000] {metadata.py:164} INFO - üîë Logged DQ signature for contacts_2025-05-24.csv: 
[2025-05-24T18:38:02.480+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-24.csv | contacts = PASS
[2025-05-24T18:38:02.915+0000] {metadata.py:109} INFO - üìù Logged stage 'validated' for contacts_2025-05-24.csv at 2025-05-24T18:38:02.497848
[2025-05-24T18:38:02.941+0000] {utils.py:52} INFO - task_metrics
[2025-05-24T18:38:02.962+0000] {main_pipeline_dag.py:27} INFO - ‚úÖ Completed task: Validate Contacts
[2025-05-24T18:38:02.978+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-24T18:38:03.055+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=marketing_data_pipeline, task_id=validate_contacts, execution_date=20250524T183640, start_date=20250524T183753, end_date=20250524T183803
[2025-05-24T18:38:03.176+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-24T18:38:03.371+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
