[2025-05-27T22:17:39.729+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Marketing_Data_Pipeline.validate_facts.validate_contacts manual__2025-05-26T00:00:00+00:00 [queued]>
[2025-05-27T22:17:39.765+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Marketing_Data_Pipeline.validate_facts.validate_contacts manual__2025-05-26T00:00:00+00:00 [queued]>
[2025-05-27T22:17:39.766+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-27T22:17:39.801+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_facts.validate_contacts> on 2025-05-26 00:00:00+00:00
[2025-05-27T22:17:39.815+0000] {standard_task_runner.py:60} INFO - Started process 1772 to run task
[2025-05-27T22:17:39.825+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Marketing_Data_Pipeline', 'validate_facts.validate_contacts', 'manual__2025-05-26T00:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/Marketing_Data_Pipeline.py', '--cfg-path', '/tmp/tmpvb5tt_iz']
[2025-05-27T22:17:39.842+0000] {standard_task_runner.py:88} INFO - Job 66: Subtask validate_facts.validate_contacts
[2025-05-27T22:17:40.043+0000] {task_command.py:423} INFO - Running <TaskInstance: Marketing_Data_Pipeline.validate_facts.validate_contacts manual__2025-05-26T00:00:00+00:00 [running]> on host 485388d78c3d
[2025-05-27T22:17:40.324+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='Marketing_Data_Pipeline' AIRFLOW_CTX_TASK_ID='validate_facts.validate_contacts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-26T00:00:00+00:00'
[2025-05-27T22:17:40.330+0000] {Marketing_Data_Pipeline.py:39} INFO - ‚ñ∂Ô∏è Starting task: Validate Contacts
[2025-05-27T22:17:40.688+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-26.csv | schema_format = PASS
[2025-05-27T22:17:40.866+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-26.csv | freshness = PASS
[2025-05-27T22:17:42.148+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-26.csv | row_count = PASS
[2025-05-27T22:17:42.278+0000] {data_validation.py:128} INFO - Valid Data for contacts_2025-05-26.csv created in /opt/***/data/validated_data
[2025-05-27T22:17:42.296+0000] {data_validation.py:144} INFO - Removed /opt/***/data/raw_data/contacts_2025-05-26.csv from raw_data folder
[2025-05-27T22:17:42.590+0000] {metadata.py:164} INFO - üîë Logged DQ signature for contacts_2025-05-26.csv: 
[2025-05-27T22:17:43.010+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-26.csv | contacts = PASS
[2025-05-27T22:17:43.470+0000] {metadata.py:109} INFO - üìù Logged stage 'validated' for contacts_2025-05-26.csv at 2025-05-27T22:17:43.027293
[2025-05-27T22:17:43.476+0000] {utils.py:56} INFO - task_metrics
[2025-05-27T22:17:43.483+0000] {Marketing_Data_Pipeline.py:41} INFO - ‚úÖ Completed task: Validate Contacts
[2025-05-27T22:17:43.488+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-27T22:17:43.538+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Marketing_Data_Pipeline, task_id=validate_facts.validate_contacts, execution_date=20250526T000000, start_date=20250527T221739, end_date=20250527T221743
[2025-05-27T22:17:43.631+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-27T22:17:43.801+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
