[2025-05-24T07:10:38.010+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T07:10:38.078+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T07:10:38.140+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-24T07:10:41.554+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): init_metadata_db> on 2025-05-23 00:00:00+00:00
[2025-05-24T07:10:41.576+0000] {standard_task_runner.py:60} INFO - Started process 367 to run task
[2025-05-24T07:10:41.631+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marketing_data_pipeline', 'init_metadata_db', 'scheduled__2025-05-23T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmp7phmnbny']
[2025-05-24T07:10:41.641+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask init_metadata_db
[2025-05-24T07:10:42.258+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [running]> on host fcb3825e40cf
[2025-05-24T07:10:42.912+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='init_metadata_db' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-23T00:00:00+00:00'
[2025-05-24T07:10:42.938+0000] {main_pipeline_dag.py:25} INFO - ‚ñ∂Ô∏è Starting task: Init Metadata DB
[2025-05-24T07:10:42.961+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main_pipeline_dag.py", line 26, in _wrapped
    fn(**kwargs)
TypeError: init_metadata_db() got an unexpected keyword argument 'conf'
[2025-05-24T07:10:43.147+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=marketing_data_pipeline, task_id=init_metadata_db, execution_date=20250523T000000, start_date=20250524T071038, end_date=20250524T071043
[2025-05-24T07:10:43.265+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task init_metadata_db (init_metadata_db() got an unexpected keyword argument 'conf'; 367)
[2025-05-24T07:10:43.429+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-24T07:10:43.703+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-24T07:20:34.198+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T07:20:34.217+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T07:20:34.219+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-24T07:20:34.259+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): init_metadata_db> on 2025-05-23 00:00:00+00:00
[2025-05-24T07:20:34.271+0000] {standard_task_runner.py:60} INFO - Started process 557 to run task
[2025-05-24T07:20:34.287+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marketing_data_pipeline', 'init_metadata_db', 'scheduled__2025-05-23T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmpgaaxqsox']
[2025-05-24T07:20:34.292+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask init_metadata_db
[2025-05-24T07:20:34.651+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [running]> on host fcb3825e40cf
[2025-05-24T07:20:35.049+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='init_metadata_db' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-23T00:00:00+00:00'
[2025-05-24T07:20:35.053+0000] {main_pipeline_dag.py:25} INFO - ‚ñ∂Ô∏è Starting task: Init Metadata DB
[2025-05-24T07:20:35.064+0000] {metadata.py:31} INFO - üîß Initializing metadata database...
[2025-05-24T07:20:35.280+0000] {metadata.py:68} INFO - ‚úÖ Metadata DB initialized.
[2025-05-24T07:20:35.295+0000] {main_pipeline_dag.py:27} INFO - ‚úÖ Completed task: Init Metadata DB
[2025-05-24T07:20:35.327+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-24T07:20:35.544+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=marketing_data_pipeline, task_id=init_metadata_db, execution_date=20250523T000000, start_date=20250524T072034, end_date=20250524T072035
[2025-05-24T07:20:36.051+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-24T07:20:36.349+0000] {taskinstance.py:3280} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2025-05-24T07:23:39.226+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T07:23:39.307+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T07:23:39.308+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-24T07:23:39.443+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): init_metadata_db> on 2025-05-23 00:00:00+00:00
[2025-05-24T07:23:39.477+0000] {standard_task_runner.py:60} INFO - Started process 627 to run task
[2025-05-24T07:23:39.529+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marketing_data_pipeline', 'init_metadata_db', 'scheduled__2025-05-23T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmp6qbswv15']
[2025-05-24T07:23:39.564+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask init_metadata_db
[2025-05-24T07:23:40.454+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [running]> on host fcb3825e40cf
[2025-05-24T07:23:42.224+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='init_metadata_db' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-23T00:00:00+00:00'
[2025-05-24T07:23:42.243+0000] {main_pipeline_dag.py:25} INFO - ‚ñ∂Ô∏è Starting task: Init Metadata DB
[2025-05-24T07:23:42.334+0000] {metadata.py:31} INFO - üîß Initializing metadata database...
[2025-05-24T07:23:43.525+0000] {metadata.py:68} INFO - ‚úÖ Metadata DB initialized.
[2025-05-24T07:23:43.594+0000] {main_pipeline_dag.py:27} INFO - ‚úÖ Completed task: Init Metadata DB
[2025-05-24T07:23:43.747+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-24T07:23:44.270+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=marketing_data_pipeline, task_id=init_metadata_db, execution_date=20250523T000000, start_date=20250524T072339, end_date=20250524T072344
[2025-05-24T07:23:44.774+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-24T07:23:45.110+0000] {taskinstance.py:3280} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2025-05-24T07:25:56.680+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T07:25:56.699+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T07:25:56.700+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-24T07:25:56.732+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): init_metadata_db> on 2025-05-23 00:00:00+00:00
[2025-05-24T07:25:56.744+0000] {standard_task_runner.py:60} INFO - Started process 686 to run task
[2025-05-24T07:25:56.751+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marketing_data_pipeline', 'init_metadata_db', 'scheduled__2025-05-23T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmp_hqe76e_']
[2025-05-24T07:25:56.755+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask init_metadata_db
[2025-05-24T07:25:56.900+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [running]> on host fcb3825e40cf
[2025-05-24T07:25:57.137+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='init_metadata_db' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-23T00:00:00+00:00'
[2025-05-24T07:25:57.140+0000] {main_pipeline_dag.py:25} INFO - ‚ñ∂Ô∏è Starting task: Init Metadata DB
[2025-05-24T07:25:57.146+0000] {metadata.py:31} INFO - üîß Initializing metadata database...
[2025-05-24T07:25:57.202+0000] {metadata.py:68} INFO - ‚úÖ Metadata DB initialized.
[2025-05-24T07:25:57.206+0000] {main_pipeline_dag.py:27} INFO - ‚úÖ Completed task: Init Metadata DB
[2025-05-24T07:25:57.209+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-24T07:25:57.251+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=marketing_data_pipeline, task_id=init_metadata_db, execution_date=20250523T000000, start_date=20250524T072556, end_date=20250524T072557
[2025-05-24T07:25:57.329+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-24T07:25:57.455+0000] {taskinstance.py:3280} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2025-05-24T08:16:08.534+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T08:16:08.825+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T08:16:08.867+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-24T08:16:10.691+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): init_metadata_db> on 2025-05-23 00:00:00+00:00
[2025-05-24T08:16:10.756+0000] {standard_task_runner.py:60} INFO - Started process 271 to run task
[2025-05-24T08:16:10.801+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marketing_data_pipeline', 'init_metadata_db', 'scheduled__2025-05-23T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmppwv8g64q']
[2025-05-24T08:16:10.846+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask init_metadata_db
[2025-05-24T08:16:12.085+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [running]> on host e6492150ec46
[2025-05-24T08:16:13.038+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='init_metadata_db' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-23T00:00:00+00:00'
[2025-05-24T08:16:13.050+0000] {main_pipeline_dag.py:25} INFO - ‚ñ∂Ô∏è Starting task: Init Metadata DB
[2025-05-24T08:16:13.075+0000] {metadata.py:31} INFO - üîß Initializing metadata database...
[2025-05-24T08:16:13.307+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main_pipeline_dag.py", line 26, in _wrapped
    fn(**kwargs)
  File "/opt/airflow/scripts/metadata.py", line 46, in init_metadata_db
    c.execute("""
sqlite3.OperationalError: near "OR": syntax error
[2025-05-24T08:16:13.416+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=marketing_data_pipeline, task_id=init_metadata_db, execution_date=20250523T000000, start_date=20250524T081608, end_date=20250524T081613
[2025-05-24T08:16:13.620+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task init_metadata_db (near "OR": syntax error; 271)
[2025-05-24T08:16:13.692+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-24T08:16:14.010+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-24T10:16:50.188+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T10:16:50.206+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [queued]>
[2025-05-24T10:16:50.207+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-24T10:16:50.232+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): init_metadata_db> on 2025-05-23 00:00:00+00:00
[2025-05-24T10:16:50.242+0000] {standard_task_runner.py:60} INFO - Started process 337 to run task
[2025-05-24T10:16:50.251+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marketing_data_pipeline', 'init_metadata_db', 'scheduled__2025-05-23T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmphg3z5rsi']
[2025-05-24T10:16:50.257+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask init_metadata_db
[2025-05-24T10:16:50.578+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_data_pipeline.init_metadata_db scheduled__2025-05-23T00:00:00+00:00 [running]> on host 8c3b47b76f3b
[2025-05-24T10:16:50.759+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='init_metadata_db' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-23T00:00:00+00:00'
[2025-05-24T10:16:50.762+0000] {main_pipeline_dag.py:25} INFO - ‚ñ∂Ô∏è Starting task: Init Metadata DB
[2025-05-24T10:16:50.766+0000] {metadata.py:31} INFO - üîß Initializing metadata database...
[2025-05-24T10:16:51.138+0000] {metadata.py:68} INFO - ‚úÖ Metadata DB initialized.
[2025-05-24T10:16:51.144+0000] {main_pipeline_dag.py:27} INFO - ‚úÖ Completed task: Init Metadata DB
[2025-05-24T10:16:51.154+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-24T10:16:51.206+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=marketing_data_pipeline, task_id=init_metadata_db, execution_date=20250523T000000, start_date=20250524T101650, end_date=20250524T101651
[2025-05-24T10:16:51.269+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-24T10:16:51.509+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
