[2025-05-25T20:13:07.190+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Marketing_Data_Pipeline.dbt_run.dbt_test manual__2025-05-25T19:37:32.889912+00:00 [queued]>
[2025-05-25T20:13:07.238+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Marketing_Data_Pipeline.dbt_run.dbt_test manual__2025-05-25T19:37:32.889912+00:00 [queued]>
[2025-05-25T20:13:07.240+0000] {taskinstance.py:2170} INFO - Starting attempt 5 of 5
[2025-05-25T20:13:07.284+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): dbt_run.dbt_test> on 2025-05-25 19:37:32.889912+00:00
[2025-05-25T20:13:07.296+0000] {standard_task_runner.py:60} INFO - Started process 21550 to run task
[2025-05-25T20:13:07.304+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Marketing_Data_Pipeline', 'dbt_run.dbt_test', 'manual__2025-05-25T19:37:32.889912+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/Marketing_Data_Pipeline.py', '--cfg-path', '/tmp/tmpmoggypwu']
[2025-05-25T20:13:07.309+0000] {standard_task_runner.py:88} INFO - Job 163: Subtask dbt_run.dbt_test
[2025-05-25T20:13:07.538+0000] {task_command.py:423} INFO - Running <TaskInstance: Marketing_Data_Pipeline.dbt_run.dbt_test manual__2025-05-25T19:37:32.889912+00:00 [running]> on host fe289fe396bd
[2025-05-25T20:13:07.878+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='Marketing_Data_Pipeline' AIRFLOW_CTX_TASK_ID='dbt_run.dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-05-25T19:37:32.889912+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-25T19:37:32.889912+00:00'
[2025-05-25T20:13:07.883+0000] {Marketing_Data_Pipeline.py:39} INFO - ‚ñ∂Ô∏è Starting task: Run all dbt tests
[2025-05-25T20:13:07.926+0000] {utils.py:100} INFO - Running dbt tests: cd /opt/dbt/marketing_pipeline && dbt test 
[2025-05-25T20:13:07.930+0000] {utils.py:65} INFO - Running dbt command: cd /opt/dbt/marketing_pipeline && dbt test 
[2025-05-25T20:13:07.965+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Marketing_Data_Pipeline.py", line 40, in _wrapped
    fn(**kwargs)
  File "/opt/airflow/scripts/utils.py", line 102, in run_dbt_test
    run_dbt(cmd)
  File "/opt/airflow/scripts/utils.py", line 85, in run_dbt
    match = re.search(r"(Done\. PASS=\d+\s+WARN=\d+\s+ERROR=\d+\s+SKIP=\d+\s+TOTAL=\d+)", full_log)
  File "/usr/local/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
[2025-05-25T20:13:08.061+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Marketing_Data_Pipeline, task_id=dbt_run.dbt_test, execution_date=20250525T193732, start_date=20250525T201307, end_date=20250525T201308
[2025-05-25T20:13:08.113+0000] {email_notification.py:58} WARNING - üìß Sending generic failure email [Airflow] Failure in Marketing_Data_Pipeline.dbt_run.dbt_test (Attempt 6/5)
[2025-05-25T20:13:08.182+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-05-25T20:13:08.184+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-05-25T20:13:09.991+0000] {email.py:281} INFO - Sent an alert email to ['yashbhawsar872@gmail.com']
[2025-05-25T20:13:11.582+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 163 for task dbt_run.dbt_test (expected string or bytes-like object; 21550)
[2025-05-25T20:13:11.646+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-25T20:13:11.821+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
