[2025-05-24T12:14:10.334+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_data_pipeline.validate_contacts manual__2025-05-24T12:12:52.903144+00:00 [queued]>
[2025-05-24T12:14:10.365+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_data_pipeline.validate_contacts manual__2025-05-24T12:12:52.903144+00:00 [queued]>
[2025-05-24T12:14:10.367+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-24T12:14:10.439+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_contacts> on 2025-05-24 12:12:52.903144+00:00
[2025-05-24T12:14:10.464+0000] {standard_task_runner.py:60} INFO - Started process 284 to run task
[2025-05-24T12:14:10.475+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'marketing_data_pipeline', 'validate_contacts', 'manual__2025-05-24T12:12:52.903144+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/tmp/tmp9pjyii7h']
[2025-05-24T12:14:10.483+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask validate_contacts
[2025-05-24T12:14:10.756+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_data_pipeline.validate_contacts manual__2025-05-24T12:12:52.903144+00:00 [running]> on host 00e321f10423
[2025-05-24T12:14:12.468+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='marketing_data_pipeline' AIRFLOW_CTX_TASK_ID='validate_contacts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-24T12:12:52.903144+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-24T12:12:52.903144+00:00'
[2025-05-24T12:14:12.477+0000] {main_pipeline_dag.py:25} INFO - ‚ñ∂Ô∏è Starting task: Validate Contacts
[2025-05-24T12:14:17.449+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-24.csv | schema_format = PASS
[2025-05-24T12:14:25.526+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-24.csv | freshness = PASS
[2025-05-24T12:14:27.241+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-24.csv | row_count = PASS
[2025-05-24T12:14:27.560+0000] {data_validation.py:139} INFO - Removed /opt/***/data/raw_data/contacts_2025-05-24.csv from raw_data folder
[2025-05-24T12:14:28.169+0000] {metadata.py:164} INFO - üîë Logged DQ signature for contacts_2025-05-24.csv: 
[2025-05-24T12:14:28.725+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-24.csv | contacts = PASS
[2025-05-24T12:14:30.907+0000] {metadata.py:109} INFO - üìù Logged stage 'validated' for contacts_2025-05-24.csv at 2025-05-24T12:14:28.734455
[2025-05-24T12:14:30.941+0000] {utils.py:52} INFO - task_metrics
[2025-05-24T12:14:31.000+0000] {main_pipeline_dag.py:27} INFO - ‚úÖ Completed task: Validate Contacts
[2025-05-24T12:14:31.038+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-24T12:14:31.173+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=marketing_data_pipeline, task_id=validate_contacts, execution_date=20250524T121252, start_date=20250524T121410, end_date=20250524T121431
[2025-05-24T12:14:31.345+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-24T12:14:31.593+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
