[2025-05-27T22:21:57.886+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Marketing_Data_Pipeline.validate_facts.validate_contacts manual__2025-05-27T00:00:00+00:00 [queued]>
[2025-05-27T22:21:57.931+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Marketing_Data_Pipeline.validate_facts.validate_contacts manual__2025-05-27T00:00:00+00:00 [queued]>
[2025-05-27T22:21:57.935+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-27T22:21:57.993+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_facts.validate_contacts> on 2025-05-27 00:00:00+00:00
[2025-05-27T22:21:58.009+0000] {standard_task_runner.py:60} INFO - Started process 2045 to run task
[2025-05-27T22:21:58.027+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Marketing_Data_Pipeline', 'validate_facts.validate_contacts', 'manual__2025-05-27T00:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/Marketing_Data_Pipeline.py', '--cfg-path', '/tmp/tmp53c75xr8']
[2025-05-27T22:21:58.033+0000] {standard_task_runner.py:88} INFO - Job 87: Subtask validate_facts.validate_contacts
[2025-05-27T22:21:58.255+0000] {task_command.py:423} INFO - Running <TaskInstance: Marketing_Data_Pipeline.validate_facts.validate_contacts manual__2025-05-27T00:00:00+00:00 [running]> on host 485388d78c3d
[2025-05-27T22:21:58.874+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashbhawsar872@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash' AIRFLOW_CTX_DAG_ID='Marketing_Data_Pipeline' AIRFLOW_CTX_TASK_ID='validate_facts.validate_contacts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-27T00:00:00+00:00'
[2025-05-27T22:21:58.878+0000] {Marketing_Data_Pipeline.py:39} INFO - ‚ñ∂Ô∏è Starting task: Validate Contacts
[2025-05-27T22:21:59.125+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-27.csv | schema_format = PASS
[2025-05-27T22:21:59.430+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-27.csv | freshness = PASS
[2025-05-27T22:22:03.862+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-27.csv | row_count = PASS
[2025-05-27T22:22:04.094+0000] {data_validation.py:128} INFO - Valid Data for contacts_2025-05-27.csv created in /opt/***/data/validated_data
[2025-05-27T22:22:04.136+0000] {data_validation.py:144} INFO - Removed /opt/***/data/raw_data/contacts_2025-05-27.csv from raw_data folder
[2025-05-27T22:22:04.458+0000] {metadata.py:164} INFO - üîë Logged DQ signature for contacts_2025-05-27.csv: 
[2025-05-27T22:22:05.660+0000] {metadata.py:144} INFO - üß™ DQ Check logged: contacts_2025-05-27.csv | contacts = PASS
[2025-05-27T22:22:06.682+0000] {metadata.py:109} INFO - üìù Logged stage 'validated' for contacts_2025-05-27.csv at 2025-05-27T22:22:05.663895
[2025-05-27T22:22:06.702+0000] {utils.py:56} INFO - task_metrics
[2025-05-27T22:22:06.978+0000] {Marketing_Data_Pipeline.py:41} INFO - ‚úÖ Completed task: Validate Contacts
[2025-05-27T22:22:07.012+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-27T22:22:07.115+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Marketing_Data_Pipeline, task_id=validate_facts.validate_contacts, execution_date=20250527T000000, start_date=20250527T222157, end_date=20250527T222207
[2025-05-27T22:22:07.307+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-27T22:22:07.568+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
